w

diff --git a/.github/workflows/compile-project-workflow.yaml b/.github/workflows/compile-project-workflow.yaml
--- a/.github/workflows/compile-project-workflow.yaml
+++ b/.github/workflows/compile-project-workflow.yaml
@@ -47,13 +47,14 @@ jobs:
         run: |
           nohup chromedriver --port=64584 --url-base=/wd/hub &
           for i in {1..10}; do
-            if curl http://localhost:64584/wd/hub/status -s | grep "200 OK" > /dev/null; then
+            if curl -s http://localhost:64584/wd/hub/status | grep '"status":0' > /dev/null; then
               echo "ChromeDriver is running on port 64584"
               break
             fi
             echo "Waiting for ChromeDriver to start..."
             sleep 2
           done
+          curl -s http://localhost:64584/wd/hub/status || echo "ChromeDriver status check failed"
 
       - name: "Compile Project"
         id: compile_project
